version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: pnpm run start:dev
